services:
  php-fpm:
    container_name: ${APP_NAME}.php-fpm
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - .:/app
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - postgresql
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  nginx:
    container_name: ${APP_NAME}.nginx
    image: nginx:alpine
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/docker/logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
#      - "443:443"

  postgresql:
    container_name: ${APP_NAME}.postgresql
    image: postgres:alpine
    volumes:
      - /var/docker/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db